jobs:
  build-job:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build Task
        run: echo "Building the application..."

  test-job:
    runs-on: self-hosted
    needs: build-job  # This makes the Test job wait for the Build job to finish
    steps:
      - name: Run Tests
        run: |
          echo "Running unit tests..."
          python -m py_compile hello.py